DROP TABLE "XACTIVITIES" CASCADE CONSTRAINTS;
DROP TABLE "XDISTRICTS" CASCADE CONSTRAINTS;
DROP TABLE "XFACILITIES" CASCADE CONSTRAINTS;
DROP TABLE "XMUNICIPALITIES" CASCADE CONSTRAINTS;
DROP TABLE "XREGIONS" CASCADE CONSTRAINTS;
DROP TABLE "XROOMTYPES" CASCADE CONSTRAINTS;
DROP TABLE "XUSES" CASCADE CONSTRAINTS;
DROP TABLE "YACTIVITIES" CASCADE CONSTRAINTS;
DROP TABLE "YDISTRICTS" CASCADE CONSTRAINTS;
DROP TABLE "YFACILITIES" CASCADE CONSTRAINTS;
DROP TABLE "YMUNICIPALITIES" CASCADE CONSTRAINTS;
DROP TABLE "YREGIONS" CASCADE CONSTRAINTS;
DROP TABLE "YROOMTYPES" CASCADE CONSTRAINTS;
DROP TABLE "YUSES" CASCADE CONSTRAINTS;
DROP TABLE "ZACTIVITIES" CASCADE CONSTRAINTS;
DROP TABLE "ZDISTRICTS" CASCADE CONSTRAINTS;
DROP TABLE "ZFACILITIES" CASCADE CONSTRAINTS;
DROP TABLE "ZMUNICIPALITIES" CASCADE CONSTRAINTS;
DROP TABLE "ZREGIONS" CASCADE CONSTRAINTS;
DROP TABLE "ZROOMTYPES" CASCADE CONSTRAINTS;
DROP TABLE "ZUSES" CASCADE CONSTRAINTS;

-- Tables
CREATE TABLE "XACTIVITIES" AS SELECT * FROM "GTD8"."ACTIVITIES";
CREATE TABLE "XDISTRICTS" AS SELECT * FROM "GTD8"."DISTRICTS";
CREATE TABLE "XFACILITIES" AS SELECT * FROM "GTD8"."FACILITIES";
CREATE TABLE "XMUNICIPALITIES" AS SELECT * FROM "GTD8"."MUNICIPALITIES";
CREATE TABLE "XREGIONS" AS SELECT * FROM "GTD8"."REGIONS";
CREATE TABLE "XROOMTYPES" AS SELECT * FROM "GTD8"."ROOMTYPES";
CREATE TABLE "XUSES" AS SELECT * FROM "GTD8"."USES";

CREATE TABLE "YACTIVITIES" AS SELECT * FROM "GTD8"."ACTIVITIES";
CREATE TABLE "YDISTRICTS" AS SELECT * FROM "GTD8"."DISTRICTS";
CREATE TABLE "YFACILITIES" AS SELECT * FROM "GTD8"."FACILITIES";
CREATE TABLE "YMUNICIPALITIES" AS SELECT * FROM "GTD8"."MUNICIPALITIES";
CREATE TABLE "YREGIONS" AS SELECT * FROM "GTD8"."REGIONS";
CREATE TABLE "YROOMTYPES" AS SELECT * FROM "GTD8"."ROOMTYPES";
CREATE TABLE "YUSES" AS SELECT * FROM "GTD8"."USES";

CREATE TABLE "ZACTIVITIES" AS SELECT * FROM "GTD8"."ACTIVITIES";
CREATE TABLE "ZDISTRICTS" AS SELECT * FROM "GTD8"."DISTRICTS";
CREATE TABLE "ZFACILITIES" AS SELECT * FROM "GTD8"."FACILITIES";
CREATE TABLE "ZMUNICIPALITIES" AS SELECT * FROM "GTD8"."MUNICIPALITIES";
CREATE TABLE "ZREGIONS" AS SELECT * FROM "GTD8"."REGIONS";
CREATE TABLE "ZROOMTYPES" AS SELECT * FROM "GTD8"."ROOMTYPES";
CREATE TABLE "ZUSES" AS SELECT * FROM "GTD8"."USES";


-- Primary Keys
ALTER TABLE "YREGIONS" ADD CONSTRAINT YREGIONS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "YDISTRICTS" ADD CONSTRAINT YDISTRICTS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "YMUNICIPALITIES" ADD CONSTRAINT YMUNICIPALITIES_COD_PK PRIMARY KEY("COD");
ALTER TABLE "YFACILITIES" ADD CONSTRAINT YFACILITIES_ID_PK PRIMARY KEY("ID");
ALTER TABLE "YROOMTYPES" ADD CONSTRAINT YROOMTYPES_ROOMTYPES_PK PRIMARY KEY("ROOMTYPE");
ALTER TABLE "YACTIVITIES" ADD CONSTRAINT YACTIVITIES_REF_PK PRIMARY KEY("REF");
ALTER TABLE "YUSES" ADD CONSTRAINT YUSES_ID_REF_PK PRIMARY KEY("ID","REF");

ALTER TABLE "ZREGIONS" ADD CONSTRAINT ZREGIONS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "ZDISTRICTS" ADD CONSTRAINT ZDISTRICTS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "ZMUNICIPALITIES" ADD CONSTRAINT ZMUNICIPALITIES_COD_PK PRIMARY KEY("COD");
ALTER TABLE "ZFACILITIES" ADD CONSTRAINT ZFACILITIES_ID_PK PRIMARY KEY("ID");
ALTER TABLE "ZROOMTYPES" ADD CONSTRAINT ZROOMTYPES_ROOMTYPES_PK PRIMARY KEY("ROOMTYPE");
ALTER TABLE "ZACTIVITIES" ADD CONSTRAINT ZACTIVITIES_REF_PK PRIMARY KEY("REF");
ALTER TABLE "ZUSES" ADD CONSTRAINT ZUSES_ID_REF_PK PRIMARY KEY("ID","REF");


-- Foreign Keys
ALTER TABLE "YDISTRICTS" ADD CONSTRAINT YDISTRICTS_REGION_FK FOREIGN KEY("REGION") REFERENCES "YREGIONS"("COD");
ALTER TABLE "YMUNICIPALITIES" ADD CONSTRAINT YMUNICIPALITIES_REGION_FK FOREIGN KEY("REGION") REFERENCES "YREGIONS"("COD");
ALTER TABLE "YMUNICIPALITIES" ADD CONSTRAINT YMUNICIPALITIES_DISTRICT_FK FOREIGN KEY("DISTRICT") REFERENCES "YDISTRICTS"("COD");
ALTER TABLE "YFACILITIES" ADD CONSTRAINT YFACILITIES_MUNICIPALITY_FK FOREIGN KEY("MUNICIPALITY") REFERENCES "YMUNICIPALITIES"("COD");
ALTER TABLE "YFACILITIES" ADD CONSTRAINT YFACILITIES_ROOMTYPE_FK FOREIGN KEY("ROOMTYPE") REFERENCES "YROOMTYPES"("ROOMTYPE");
ALTER TABLE "YUSES" ADD CONSTRAINT YUSES_ID_FK FOREIGN KEY("ID") REFERENCES "YFACILITIES"("ID");
ALTER TABLE "YUSES" ADD CONSTRAINT YUSES_REF_FK FOREIGN KEY("REF") REFERENCES "YACTIVITIES"("REF");

ALTER TABLE "ZDISTRICTS" ADD CONSTRAINT ZDISTRICTS_REGION_FK FOREIGN KEY("REGION") REFERENCES "ZREGIONS"("COD");
ALTER TABLE "ZMUNICIPALITIES" ADD CONSTRAINT ZMUNICIPALITIES_REGION_FK FOREIGN KEY("REGION") REFERENCES "ZREGIONS"("COD");
ALTER TABLE "ZMUNICIPALITIES" ADD CONSTRAINT ZMUNICIPALITIES_DISTRICT_FK FOREIGN KEY("DISTRICT") REFERENCES "ZDISTRICTS"("COD");
ALTER TABLE "ZFACILITIES" ADD CONSTRAINT ZFACILITIES_MUNICIPALITY_FK FOREIGN KEY("MUNICIPALITY") REFERENCES "ZMUNICIPALITIES"("COD");
ALTER TABLE "ZFACILITIES" ADD CONSTRAINT ZFACILITIES_ROOMTYPE_FK FOREIGN KEY("ROOMTYPE") REFERENCES "ZROOMTYPES"("ROOMTYPE");
ALTER TABLE "ZUSES" ADD CONSTRAINT ZUSES_ID_FK FOREIGN KEY("ID") REFERENCES "ZFACILITIES"("ID");
ALTER TABLE "ZUSES" ADD CONSTRAINT ZUSES_REF_FK FOREIGN KEY("REF") REFERENCES "ZACTIVITIES"("REF");
