CREATE UNIQUE INDEX INDEX_ZACTIVITY_ACTIVITIES ON ZACTIVITIES (REF, ACTIVITY);
CREATE UNIQUE INDEX INDEX_ZDISTRICTS_COD ON ZDISTRICTS (COD, DESIGNATION);
CREATE UNIQUE INDEX INDEX_ZFACILITIES_MUNICIPALITY ON ZFACILITIES (ID, MUNICIPALITY);
CREATE UNIQUE INDEX INDEX_ZMUNICIPALITIES_REGION ON ZMUNICIPALITIES (COD, REGION);
CREATE UNIQUE INDEX INDEX_ZMUNICIPALITIES_DISTRICT ON ZMUNICIPALITIES (COD, DISTRICT);
CREATE UNIQUE INDEX INDEX_ZREGIONS_DESIGNATION ON ZREGIONS (COD, DESIGNATION);
CREATE UNIQUE INDEX INDEX_ZROOMTYPES_ROOMTYPE ON ZROOMTYPES (ROOMTYPE, DESCRIPTION);

---- Index for 5 a)
CREATE INDEX INDEX_B_TREE ON ZFACILITIES (ROOMTYPE, MUNICIPALITY);

---- Index for 5 b)
CREATE BITMAP INDEX INDEX_BITMAP ON ZFACILITIES (ROOMTYPE, MUNICIPALITY);