-- 1
DROP INDEX "INDEX_ZACTIVITY_ACTIVITIES";
DROP INDEX "INDEX_ZROOMTYPES_ROOMTYPE";
CREATE UNIQUE INDEX INDEX_ZACTIVITY_ACTIVITIES ON ZACTIVITIES (ACTIVITY ASC);
CREATE UNIQUE INDEX INDEX_ZROOMTYPES_ROOMTYPE ON ZROOMTYPES (ROOMTYPE ASC, DESCRIPTION ASC);

-- 2
DROP INDEX "INDEX_ZROOMTYPES_ROOMTYPE";
DROP INDEX "INDEX_ZREGIONS_DESIGNATION";
CREATE UNIQUE INDEX INDEX_ZROOMTYPES_ROOMTYPE ON ZROOMTYPES (ROOMTYPE ASC, DESCRIPTION ASC);
CREATE UNIQUE INDEX INDEX_ZREGIONS_DESIGNATION ON ZREGIONS (COD ASC, DESIGNATION ASC);