DROP TABLE "ACTIVITIES" CASCADE CONSTRAINTS;
DROP TABLE "DISTRICTS" CASCADE CONSTRAINTS;
DROP TABLE "FACILITIES" CASCADE CONSTRAINTS;
DROP TABLE "MUNICIPALITIES" CASCADE CONSTRAINTS;
DROP TABLE "REGIONS" CASCADE CONSTRAINTS;
DROP TABLE "ROOMTYPES" CASCADE CONSTRAINTS;
DROP TABLE "USES" CASCADE CONSTRAINTS;

CREATE TABLE "ACTIVITIES" AS SELECT * FROM "GTD8"."ACTIVITIES";
CREATE TABLE "DISTRICTS" AS SELECT * FROM "GTD8"."DISTRICTS";
CREATE TABLE "FACILITIES" AS SELECT * FROM "GTD8"."FACILITIES";
CREATE TABLE "MUNICIPALITIES" AS SELECT * FROM "GTD8"."MUNICIPALITIES";
CREATE TABLE "REGIONS" AS SELECT * FROM "GTD8"."REGIONS";
CREATE TABLE "ROOMTYPES" AS SELECT * FROM "GTD8"."ROOMTYPES";
CREATE TABLE "USES" AS SELECT * FROM "GTD8"."USES";

-- Primary Keys
ALTER TABLE "REGIONS" ADD CONSTRAINT REGIONS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "DISTRICTS" ADD CONSTRAINT DISTRICTS_COD_PK PRIMARY KEY("COD");
ALTER TABLE "MUNICIPALITIES" ADD CONSTRAINT MUNICIPALITIES_COD_PK PRIMARY KEY("COD");
ALTER TABLE "FACILITIES" ADD CONSTRAINT FACILITIES_ID_PK PRIMARY KEY("ID");
ALTER TABLE "ROOMTYPES" ADD CONSTRAINT ROOMTYPES_ROOMTYPES_PK PRIMARY KEY("ROOMTYPE");
ALTER TABLE "ACTIVITIES" ADD CONSTRAINT ACTIVITIES_REF_PK PRIMARY KEY("REF");
ALTER TABLE "USES" ADD CONSTRAINT USES_ID_REF_PK PRIMARY KEY("ID","REF");

-- Foreign Keys
ALTER TABLE "DISTRICTS" ADD CONSTRAINT DISTRICTS_REGION_FK FOREIGN KEY("REGION") REFERENCES "REGIONS"("COD");
ALTER TABLE "MUNICIPALITIES" ADD CONSTRAINT MUNICIPALITIES_REGION_FK FOREIGN KEY("REGION") REFERENCES "REGIONS"("COD");
ALTER TABLE "MUNICIPALITIES" ADD CONSTRAINT MUNICIPALITIES_DISTRICT_FK FOREIGN KEY("DISTRICT") REFERENCES "DISTRICTS"("COD");
ALTER TABLE "FACILITIES" ADD CONSTRAINT FACILITIES_MUNICIPALITY_FK FOREIGN KEY("MUNICIPALITY") REFERENCES "MUNICIPALITIES"("COD");
ALTER TABLE "FACILITIES" ADD CONSTRAINT FACILITIES_ROOMTYPE_FK FOREIGN KEY("ROOMTYPE") REFERENCES "ROOMTYPES"("ROOMTYPE");
ALTER TABLE "USES" ADD CONSTRAINT USES_ID_FK FOREIGN KEY("ID") REFERENCES "FACILITIES"("ID");
ALTER TABLE "USES" ADD CONSTRAINT USES_REF_FK FOREIGN KEY("REF") REFERENCES "ACTIVITIES"("REF");